[BE] Implement products flow
ZaytsevGleb/ComputerStore pull request #1
Opened 2023-07-27 12:55 UTC by ZaytsevGleb

2023-07-31 10:28 UTC, GodlyCat requested changes

2023-07-31 10:28 UTC, GodlyCat commented on BusinessLogic/BusinessLogic.csproj
> +    <PackageReference Include="Serilog" Version="3.0.1" />
Why this not in api layer ?

2023-07-31 10:28 UTC, GodlyCat commented on BusinessLogic/Products/Services/ProductService.cs
> -            throw new NotFoundException("");
Remove this validation for get by id operations
Case, when we trying to get not existing entity - valid
And should be handled by front for ex.

2023-07-31 10:28 UTC, GodlyCat commented on BusinessLogic/Products/Services/ProductService.cs
> +        var product = new Product
why not automapper ?

2023-07-31 10:28 UTC, GodlyCat commented on BusinessLogic/Products/Services/ProductService.cs
> +        product.Title = productModel.Title;
why not automapper ?

2023-07-31 10:28 UTC, GodlyCat commented on BusinessLogic/Products/Services/ProductService.cs
> +            _logger.LogError($"Product with id: {id} was not found");
Not use interpolation for logs, use string parameters

2023-07-31 10:28 UTC, GodlyCat commented on DataAccess/Infrastructure/SeedData.cs
> +                Title = "Видеокарта BIOSTAR GeForce RTX 3070 8GB GDDR6 VN3706RM82",
Please don't use ru language

2023-07-31 10:28 UTC, GodlyCat commented on DataAccess/Repositories/Repository.cs
> +    public async Task<TEntity?> GetAsync(Guid id)
Please add asNoTracking

2023-07-31 10:28 UTC, GodlyCat commented on DataAccess/Repositories/Repository.cs
> +    public async Task<List<TEntity>> FindAsync(Expression<Func<TEntity, bool>>? predicate = null)
Use or get or find in all methods

2023-07-31 10:28 UTC, GodlyCat commented on DataAccess/Repositories/Repository.cs
> +    public async Task DeleteAsync(TEntity item)
Maybe Async word from method name could be removed (depends on your wish)

2023-07-31 10:28 UTC, GodlyCat commented on UnitTests/Products/ProductDtoValidatorTests.cs
> +public sealed class ProductDtoValidatorTests
sealed ?

2023-07-31 10:28 UTC, GodlyCat commented on WebAPI/Controllers/ProductsController.cs
>      public async Task<ActionResult<IEnumerable<ProductDto>>> GetProductsAsync([FromQuery] ProductSearchDto searchDto)
Better to avoid action results and handle status codes can be handled by exception middleware

2023-07-31 10:28 UTC, GodlyCat commented on WebAPI/Middleware/ErrorHandlingMiddleware.cs
Rename to exception middleware

2023-07-31 10:28 UTC, GodlyCat commented on WebAPI/Program.cs
> +    public static async Task Main(string[] args)
Why we need startup and program. In .net 6 both combined in program.cs

2023-07-31 13:35 UTC, ZaytsevGleb commented on DataAccess/Repositories/Repository.cs
> +    public async Task DeleteAsync(TEntity item)
I prefer the Async prefix

2023-07-31 13:57 UTC, ZaytsevGleb commented on DataAccess/Repositories/Repository.cs
> +    public async Task DeleteAsync(TEntity item)
I prefer with Async prefix.

2023-07-31 14:01 UTC, ZaytsevGleb commented on WebAPI/Program.cs
> +    public static async Task Main(string[] args)
It's more readable for me, but if you're just using the program, I'd follow your code style.

2023-08-01 07:14 UTC, moltenessence commented on BusinessLogic/Products/Services/ProductService.cs
> +        return products.Select(_mapper.Map<ProductModel>);
Why not to map to IEnumerable directly instead mapping of each product separately using select?

2023-08-01 07:14 UTC, moltenessence commented on BusinessLogic/Products/Services/ProductService.cs
> +        var products = await _repository.FindAsync(x => x.Title == productModel.Title);
If we have a lot of productsm such approach could affect performance. I mean, it's not so good to get all the entities from db just to check if product with such title exists or not. Better approach would be to return true when we meet the first entity which satisfies prediciate

2023-08-01 07:14 UTC, moltenessence commented on BusinessLogic/Products/Services/ProductService.cs
> +        productModel.ModifiedDate = _dateTimeService.UtcNow;
You can use EF interceptors for this purpose (the same for creation date)

2023-08-01 07:14 UTC, moltenessence commented on DataAccess/Configurations/ProductsConfiguration.cs
> +        builder.ToTable("Products", "dbo");
Is it really necessary?

2023-08-01 07:14 UTC, moltenessence commented on UnitTests/Products/ProductDtoValidatorTests.cs
> +        var product = new ProductDto
move test data to separate file

2023-08-01 07:14 UTC, moltenessence commented on WebAPI/Program.cs
> +            using var scope = application.Services.CreateScope();
Can we move it to dal layer?

2023-08-01 07:14 UTC, moltenessence commented on WebAPI/Program.cs
> +            .AddDataAccessDependencies(builder.Configuration)
API layer should not contain any dependencies from DAL. Even extensions for DI

2023-08-01 07:26 UTC, ZaytsevGleb commented on WebAPI/Program.cs
> +            .AddDataAccessDependencies(builder.Configuration)
This is happening because of ProductType enum, I want to create an Entities layer to solve this problem

2023-08-03 01:37 UTC, GodlyCat approved these changes

2023-08-03 07:09 UTC, merged